/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2180609013luthanhy;

/**
 *
 * @author Administrator
 */
public class GuiEncryption extends javax.swing.JFrame {

    private String CheckMethodEncryption = null;
    private Ceasar EncrytionByCeasar = new Ceasar();
    /**
     * Creates new form GuiEncryption
     */
    public GuiEncryption() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogCheckPlainText = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        ButtonDecrypt = new javax.swing.JButton();
        ButtonOpenFile = new javax.swing.JButton();
        TextInput = new javax.swing.JTextField();
        TextKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxMethodEncryption = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TextOutput = new javax.swing.JTextField();
        ButtonWriteFile = new javax.swing.JButton();
        ButtonEncrypt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel7.setText("Please Enter Value ");
        DialogCheckPlainText.getContentPane().add(jLabel7, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ButtonDecrypt.setText("Decrypt");
        getContentPane().add(ButtonDecrypt);
        ButtonDecrypt.setBounds(430, 770, 90, 40);

        ButtonOpenFile.setText("OpenFile");
        ButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpenFileActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonOpenFile);
        ButtonOpenFile.setBounds(830, 770, 90, 40);

        TextInput.setText("Enter Value Encryption");
        TextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextInputActionPerformed(evt);
            }
        });
        getContentPane().add(TextInput);
        TextInput.setBounds(430, 480, 490, 70);

        TextKey.setText("Enter Key");
        getContentPane().add(TextKey);
        TextKey.setBounds(430, 620, 490, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plain Text:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 500, 250, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Key :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 600, 250, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cipher Text :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 700, 250, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Program Encryption / Decription (CEASAR And VIGENERE)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 240, 1030, 60);

        ComboBoxMethodEncryption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEASAR", "VIGENERE" }));
        ComboBoxMethodEncryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMethodEncryptionActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxMethodEncryption);
        ComboBoxMethodEncryption.setBounds(430, 410, 490, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Method encryption :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 400, 250, 50);

        TextOutput.setText("Result ...");
        TextOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOutputActionPerformed(evt);
            }
        });
        getContentPane().add(TextOutput);
        TextOutput.setBounds(430, 680, 490, 70);

        ButtonWriteFile.setText("WriteFile");
        ButtonWriteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWriteFileActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonWriteFile);
        ButtonWriteFile.setBounds(830, 565, 90, 40);

        ButtonEncrypt.setText("Encription");
        ButtonEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEncryptActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEncrypt);
        ButtonEncrypt.setBounds(430, 565, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/y.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 180, 1000, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpenFileActionPerformed

    private void ButtonWriteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWriteFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonWriteFileActionPerformed

    private void ButtonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEncryptActionPerformed
            if(CheckMethodEncryption == "CEASAR"){
            if(TextInput.getText().isEmpty()){
                System.out.print("Success CEASAR" + DialogCheckPlainText.getName());
                DialogCheckPlainText.setVisible(true);
            }else{
                System.out.print("Success CEASAR");
            }
        }else if(CheckMethodEncryption == "VIGENERE"){
        }else{
        }

    }//GEN-LAST:event_ButtonEncryptActionPerformed

    private void TextOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextOutputActionPerformed
    

    
    private void ComboBoxMethodEncryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMethodEncryptionActionPerformed
        Object selectComboBoxMethod =  ComboBoxMethodEncryption.getSelectedItem();
        if(selectComboBoxMethod != null){
            CheckMethodEncryption = selectComboBoxMethod.toString();
        }else{
            // no code
        }
        System.out.println("CheckMethodEncryption: " + CheckMethodEncryption);
    }//GEN-LAST:event_ComboBoxMethodEncryptionActionPerformed

    private void TextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextInputActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_TextInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEncryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDecrypt;
    private javax.swing.JButton ButtonEncrypt;
    private javax.swing.JButton ButtonOpenFile;
    private javax.swing.JButton ButtonWriteFile;
    private javax.swing.JComboBox ComboBoxMethodEncryption;
    private javax.swing.JDialog DialogCheckPlainText;
    private javax.swing.JTextField TextInput;
    private javax.swing.JTextField TextKey;
    private javax.swing.JTextField TextOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
